name: netlogger
description: A simple binary that logs datas/file content or stdin into a network socket.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies: {args: ^2.3.1, dartzmq: ^1.0.0-dev.10}

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
